#!/bin/sh

# Add all the files in the current directory to the Git index

git add .

# Commit the changes with a message

git commit -m "Automatic commit from script"


# Push the changes to the remote repository

git push origin master
